name: Build Flutter Web and Deploy to Vercel

on:
  push:
    branches:
      - main  # o la rama que quieras

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4' # o la versión que uses

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        env:
          STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        run: flutter build web --release --dart-define=STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY --dart-define=STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npm install -g vercel
          vercel deploy build/web --prod --token $VERCEL_TOKEN --confirm --project $VERCEL_PROJECT_ID --scope $VERCEL_ORG_ID
